### ISSUE TITLE
Saving Workflow

### ISSUE THREAD

**Issue by karenangella** [BioDepot/BioDepot-workflow-builder#59]
I was running the base jupyter notebook widget on AWS ec2 m5.xlarge. It opens the jupyter notebook windows just fine and I stopped the widget from running. But when I tried to save the workflow that contains the jupyter notebook, it gives me this errors: 

Exception:
shutil.Error: [('/widgets/Jupyter/jupyter_base/Dockerfiles/.mozilla/firefox/6v20d6ix.default-release/lock', '/tmp/tmp21bp4vc0/widgets/seurat/jupyter_base/Dockerfiles/.mozilla/firefox/6v20d6ix.default-release/lock', "[Errno 2] No such file or directory: '/widgets/Jupyter/jupyter_base/Dockerfiles/.mozilla/firefox/6v20d6ix.default-release/lock'")]
Module:
shutil:365
Widget Scheme:
/tmp/ows-h1fzkkx1.ows.xml
Version:
3.14.0.dev0+Unknown
Environment:
Python 3.6.9 on Linux 6.1.23-36.46.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Apr 10 22:43:13 UTC 2023 x86_64
Installed Packages:
AnyQt==0.2.0, Bottleneck==1.3.6, CommonMark==0.7.5, Jupyter==0.0.0, Miscellaneous==0.0.0, Orange3==3.14.0.dev0+unknown, RNA-seq==0.0.0, Scripting==0.0.0, SecretStorage==2.3.1, User==0.0.0, Utilities==0.0.0, asn1crypto==0.24.0, beautifulsoup4==4.11.2, certifi==2022.12.7, chardet==5.0.0, charset-normalizer==2.0.12, cryptography==2.1.4, docker==5.0.3, docutils==0.18.1, future==0.18.3, idna==2.6, importlib-metadata==4.8.3, joblib==1.1.1, jsonpickle==2.2.0, keyring==10.6.0, keyrings.alt==3.0, numpy==1.19.5, pip==20.0.1, pycrypto==2.6.1, pygobject==3.26.1, pyqtgraph==0.11.1, pysam==0.20.0, pyxdg==0.25, requests==2.27.1, scikit-learn==0.24.2, scipy==1.5.4, serverfiles==0.3.1, setuptools==59.6.0, six==1.11.0, soupsieve==2.3.2.post1, threadpoolctl==3.1.0, typing-extensions==4.1.1, urllib3==1.26.14, websocket-client==1.3.1, wheel==0.37.1, xlrd==2.0.1, zipp==3.6.0
Machine ID:
2485377892354
Stack Trace:
Traceback (most recent call last):
  File "/orange3/Orange/canvas/application/canvasmain.py", line 1608, in save_scheme_as
    iconFile=self.saveWorkflowSettings["icon"],
  File "/coreutils/workflowTools.py", line 325, in exportWorkflow
    shutil.copytree(widgetPath, uniquePath)
  File "/usr/lib/python3.6/shutil.py", line 365, in copytree
    raise Error(errors)
shutil.Error: [('/widgets/Jupyter/jupyter_base/Dockerfiles/.mozilla/firefox/6v20d6ix.default-release/lock', '/tmp/tmp21bp4vc0/widgets/seurat/jupyter_base/Dockerfiles/.mozilla/firefox/6v20d6ix.default-release/lock', "[Errno 2] No such file or directory: '/widgets/Jupyter/jupyter_base/Dockerfiles/.mozilla/firefox/6v20d6ix.default-release/lock'")]

Local Variables:
OrderedDict([('copy_function', <function copy2 at 0x7f9b3c6d0bf8>),
             ('dst', '/tmp/tmp21bp4vc0/widgets/seurat/jupyter_base'),
             ('dstname',
              '/tmp/tmp21bp4vc0/widgets/seurat/jupyter_base/jupyter_base.states'),
             ('errors',
              [('/widgets/Jupyter/jupyter_base/Dockerfiles/.mozilla/firefox/6v20d6ix.default-release/lock',
                '/tmp/tmp21bp4vc0/widgets/seurat/jupyter_base/Dockerfiles/.mozilla/firefox/6v20d6ix.default-release/lock',
                '[Errno 2] No such file or directory: '
                "'/widgets/Jupyter/jupyter_base/Dockerfiles/.mozilla/firefox/6v20d6ix.default-release/lock'")]),
             ('ignore', None),
             ('ignore_dangling_symlinks', False),
             ('ignored_names', set()),
             ('name', 'jupyter_base.states'),
             ('names',
              ['Dockerfiles',
               'icon',
               'jupyter_base.attrs',
               'jupyter_base.json',
               'jupyter_base.py',
               'jupyter_base.states']),
             ('src', '/widgets/Jupyter/jupyter_base'),
             ('srcname', '/widgets/Jupyter/jupyter_base/jupyter_base.states'),
             ('symlinks', False)])

<img width="1380" alt="Screen Shot 2023-04-21 at 8 58 12 PM" src="https://user-images.githubusercontent.com/55929761/233761624-916b532d-801e-4524-aeee-202c03966393.png">

**Comment by lhhunghimself** [comment]
Save the workflow first and then run. You are running from a symlink which
is locked after you ran it for some reason. If you make a copy first, this
is no longer a problem.

Hong
